* Peace and happiness depends on the sensations of fluctuations in the mind.
This makes sense to me because the buddha first felt true peace when he sat as a youth and felt totally content, because he didnt want anything.

* Apathy is a kind of numbness, where in response to internal drivers, positive or negative, like ambition or loneliness, we just check out mentally and numb ourselves to the negative experiences.

* Ambition leads to burn out
what is ambition? how does it lead to burn out?

* Many people cannot afford to give up their attachments, because then they would lose their motivation to continue on in life.
attachments here include ambition and anxiety.

* Detachment is not about detaching from the world. it is about detaching from your self.
sense

* is the sense of self the same as the ego?
yes

* Detachment is about getting rid of the attachment to the idea of self
When you detach from the idea of self, you become more towards the world, because now there is not the filter of self separating you from the world. This connection to the world also helps spirituality.

* Detachment is the foundation to spirituality
If spirituality is the understanding that you are connected to all things, and then some detachment has to happen, in order to make the realization that you are connected to everything.

* When you care about what other people think, the only thing that you really care about is their opinion of you

* Apathy and detachment are opposites, because detachment is about moving towards the world, and apathy is moving away from the world, removing yourself from it.

* The resistance you feel to doing things is usually from your own emotions and ego.
how does emotions come into play from the sense of self? if sense of self is a view, and i think a really fundamental base view at that, and our emotions are shaped by our views, then it makes sense that most of our negative emotions come from this idea of self.

* how does views shape our emotions?

* does our positive emotions only come from detachment? like happiness and peace and joy and all that. or can positive emotions come from attachment too? if they could come from attachment, would there be baggage with those emotions, like not being able to enjoy them fully?

* Detachment lowers the resistance to doing things, because remember that the resistance you feel is comprised of emotions and the idea of self, which is removed when you become detached.

* When you become detached, there are all kinds of motivators that come up, like curiosity.

* social anxiety is the concern of what other people will think about you.

* if you hate something, really ask yourself why you hate it.
you might find that you hate the job because of all the attachments that you have related to the job.

* attachment and ego are the things that hold us back in life.
how does ambition play a part in attachment and ego?

* What would life be like if you had no resistance to what you wanted to do?
like no fear or anxiety holding you back.

* one of the most important ways of cultivating detachment is through awareness
isnt awareness on the noble eightfold path?

* awareness -> understanding -> control
for example, if you are at the dentist and they numb your gums, you
cant actually control your gums. The same thing happens in life, if you are unaware of what is going on in your life, you cant understand it, and therefore control it.
* Apathy is the best numbing agent
what causes me to check out mentally? to not care?

* Apathy is the opposite of awareness, because you cannot be aware of something while you are numb to it

* Meditation is the best way to cultivate awareness
also spending time with yourself

* we find our attachments in our reactions to things.

* Mistakes of passion
- passion is a career or a job
- 
* what is interdependence?

* life is not worth living without other people
this kinda reminds me of the viktor frankl quote from mans search for meaning "only 3 things that can give meaning, love, your work, and suffering" or something like that. i have to look up what the actual quote is lol.

* what is the process of dealing with negative emotions?
- what is venting emotions?
- most commonly people distract themselves with technology, like video games and social media, which might be a form of apathy, because by doing those things you are numbing yourself to your internal signals of negative emotion
- the more negative emotion that is packed in, the more energy that it takes to keep it suppressed. this decreases motivation and available energy. its like a load on the mind
- negative emotions often are self perpetutaing cycles
- 4 steps to emotional processing:
  1. be aware of the emotion
  2. explore the origin of the emotion
  3. intentionally alter your behavior in the moment in response to the emotion
  4. reintegrate your negative experience into identity
     involves reframing
* what is the process of suppressing emotions according to the buddha

* what emotions are not processed is stored, and what is stored can be recalled

* emotional baggage is leftover emotion that has not been processed

* burnout can commonly happen in people who have a good life, like a good job and a good relationships

* burnout is firstly characterized by a lack of energy.

* people will also make excuses for and devalue their experiences

* the first phase of burnout is a lack of empathy
you stop caring about other people, which manifests as cynicism. This includes lack of self-empathy. you lose sight of the people involved and what actually matters.

* empathy requires energy for other people

* lack of enjoyment or fulfillment with your job

* tending to have a short fuse

* burnout and depression are not the same thing
depression is something that you carry with you. burnout is the intersection in between you and your job

* 6 factors of burnout
1. Workload
2. Control
3. Reward
4. Community
5. Fairness
6. Values - people want to be challenged and want to be valued

* being challenged and succeeding leads to a sense of fulfillment. people noticing the effort that you put in also leads to fulfillment.

* being apathetic to your successes has 2 components
1. being apathetic towards your success is an avoidance strategy that helps emotionally regulate.
2. divorcing yourself from success to numb yourself in the case of failure, because people with adhd have trouble putting in the work to succeed.

* people with adhd ability to regulate emotions results in 3 coping strategies
1. avoidance - mentally check out, apathy, avoid the thing entirely
2. suppression
3. reappraisal - working through the emotion and dealing with the emotion 
* The absence of evil does not indicate the presence of good
* Goodness is proactive, not just not doing bad things.
* Goodness is caring about people
* Goodness is applied detachment, that you understand that you are connected to everything else and you should help them because it is the right thing to do
* Often the most dangerous man in the room is the quietest one
* You cant be a fully good man if you arent a dangerous man, because sometimes doing good to people means protecting them, and you cant protect them well if you are not dangerous
* Be calm. Walk away from the things that stress you out.
